version: '3.5'

services:
  my-app:
    build: .
    expose:
      - "8080"
    network_mode: bridge
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://database-client.cnk2ykjwwh2q.us-east-1.rds.amazonaws.com:5432/postgres
      - DB_USER=postgres
      - DB_PASS=6KNnqhZX2dCIPnzQi0uL
