version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://database-client.cnk2ykjwwh2q.us-east-1.rds.amazonaws.com:5432/postgres
      - DB_USER=postgres
      - DB_PASS=6KNnqhZX2dCIPnzQi0uL
